import YoutubeEmbed from '@/components/mdx/YoutubeEmbed';
import Link from 'next/link';
import Image from 'next/image';
import FAQ from '@/components/for-businesses/FAQ';
import ClientTestimonial from '@/components/offers/ClientTestimonial';
import CallToAction from '@/components/offers/CallToAction';
import Divider from '@/components/offers/Divider';

function page() {
 const resultsData = [
  {
   id: 1,
   percentage: '23',
   detail:
    'Decrease in Cost Per Acquisition (CPA) by 23%. Proper tracking allows for more efficient ad targeting and budget allocation, leading to a significant reduction in the cost to acquire a new customer.',
  },
  {
   id: 2,
   percentage: '37',
   detail:
    'Increase in Return on Ad Spend (ROAS) by 37%. With accurate conversion tracking, businesses can optimize their ad campaigns for better performance, resulting in a higher return on their advertising investments.',
  },
  {
   id: 3,
   percentage: '19',
   detail:
    'Improvement in conversion attribution accuracy by 19%. Enhanced tracking provides clearer insights into the customer journey, allowing businesses to attribute conversions more accurately to the correct marketing channels.',
  },
  {
   id: 4,
   percentage: '27',
   detail:
    'Increase in Customer Lifetime Value (LTV) by 27%. By understanding customer behavior through detailed analytics, businesses can tailor their marketing strategies to increase the overall value generated by each customer over time.',
  },
 ];

 const someReasonsData = [
  {
   id: 1,
   title: 'Clear, Actionable Insights',
   paragraph:
    'Get straightforward insights from your data without complex setups. We make your data work for you, providing clear, actionable insights for growth.',
   imageUrl: '/images/for-businesses/reason-data-001.png',
  },
  {
   id: 2,
   title: 'Unique Problems, Custom Solutions',
   paragraph:
    'We tailor solutions to your unique needs, from sensible ecommerce tracking to analytics for decision-making. Enjoy better decisions, more conversions, and clearer goals.',
   imageUrl: '/images/for-businesses/reason-data-002.png',
  },
  {
   id: 3,
   title: 'Fast, Efficient, and Transparent',
   paragraph:
    'We set up your tracking quickly, keep you informed, and ensure transparency in costs. No hidden fees, just honest work for your business growth.',
   imageUrl: '/images/for-businesses/reason-data-003.png',
  },
  {
   id: 4,
   title: "Reports You'll Actually Read",
   paragraph:
    'Our reports are like a chat with a knowledgeable friend. Easy to read, understand, and use. No jargon or endless tables, just useful insights.',
   imageUrl: '/images/for-businesses/reason-data-004.png',
  },
 ];

 const images = {
  group: {
   list: [
    {
     src: '/images/clients/001_1.jfif',
     alt: 'Imtiaz Ahmed - Job Ready Programmer',
    },
    { src: '/images/clients/007.jfif', alt: 'Client' },
    {
     src: '/images/clients/008.jfif',
     alt: 'Pjipipp Herglotz - Kiss Agency',
    },
    {
     src: '/images/clients/001.jpg',
     alt: 'Imtiaz Ahmed - Job Ready Programmer',
    },
    {
     src: '/images/clients/001.jpg',
     alt: 'Imtiaz Ahmed - Job Ready Programmer',
    },
   ],
  },
  background: {
   desktop: '/images/hero/hero-image-md.png',
   mobile: '/images/hero/hero-image-sm.png',
  },
 };

 return (
  <main>
   <section className='pt-6 pb-2 space-y-2'>
    <h1 className='text-center text-3xl md:text-4xl font-semibold '>
     <span className='text-primary'>Get 95% Accurate Tracking</span> in 7 Days –
     Guaranteed! Turn your data into{' '}
     <span className='text-primary'>easy-to-use insights </span> and{' '}
     <span className='text-primary'>see your profits grow quickly</span>.
    </h1>

    <div className='flex justify-center'>
     <YoutubeEmbed embedId={'9MGpL_AmEYM'} />
    </div>
    <h3 className=' text-2xl md:text-3xl font-bold text-center py-2'>
     Ready to see how it works? Watch the video and apply below!
    </h3>
    <div className='text-center '>
     <Link
      href='/offers/95-accurate-tracking-in-7-days/submit-query'
      className='link-primary-danger text-2xl !px-12'>
      Apply Now
     </Link>
    </div>
   </section>

   <Divider />
   <section className=' space-y-3'>
    <h3 className=' text-3xl md:text-4xl font-semibold text-center py-2'>
     Improve Your Tracking with Proven Results. Here’s How:
    </h3>
    <p>
     We make sure your tracking is accurate with an easy setup, full testing,
     and low maintenance. Our system helps you make better decisions and
     increase your profits.
    </p>
    <div className='space-y-3'>
     <h4 className='text-4xl font-semibold text-primary'>
      Fast Implementation
     </h4>
     <p>
      We set up your tracking system in 7 days. Our team handles everything to
      make sure it works smoothly with no downtime.
     </p>
    </div>

    <div className='space-y-3'>
     <h4 className='text-4xl font-semibold text-primary'>High Accuracy</h4>
     <p>
      Get 95% accuracy, which helps you make better decisions and increase your
      profits. Our system is easy to keep running with low costs.
     </p>
    </div>

    <div className='space-y-3'>
     <h4 className='text-4xl font-semibold text-primary'>Ease of Use</h4>
     <p>
      Our system is simple and doesn’t need much technical knowledge. It grows
      with your business while staying accurate and efficient.
     </p>
    </div>
    <div className='space-y-3'>
     <h4 className='text-4xl font-semibold text-primary'>The End Result?</h4>
     <p>
      We are so sure of our process that we guarantee 95% tracking accuracy in 7
      days, or you get a full refund. Enjoy 24/7 support from our customer
      service team.
     </p>
     <p>
      See the difference our system makes and take your business to the next
      level. Book a free consultation now and secure your spot before it’s too
      late!
     </p>
    </div>

    <div className='text-center py-2'>
     <Link
      href='/offers/95-accurate-tracking-in-7-days/submit-query'
      className='link-primary-danger text-2xl !px-12'>
      Schedule Your Call
     </Link>
    </div>
   </section>
   <Divider />
   <ClientTestimonial />
   <CallToAction />
  </main>
 );
}

export default page;
