import Link from "next/link";
import React from "react";
import { Poppins } from "next/font/google";
import CaseStudies from "@/components/home/CaseStudies";
import ImageSlider from "@/components/home/ImageSlider";
import MobileNav from "@/components/home/MobileNav";
import DesktopNav from "@/components/home/DesktopNav";
import Image from "next/image";
import Timeline from "@/components/home/Timeline";
import Technologies from "@/components/home/Technologies";
import ComparisonTable from "@/components/home/ComparisonTable";
import FAQ from "@/components/home/FAQ";
import Footer from "@/components/footer/Footer";
import Hero from "@/components/home/Hero";
import WorkHistory from "@/components/home/WorkHistory";
import ReasonsData from "@/components/home/ReasonsData";
import ReasonsData02 from "@/components/home/ReasonsData02";
import CallToAction from "@/components/home/CallToAction";
const poppins = Poppins({
 subsets: ["latin"],
 display: "swap",
 variable: "--font-poppins",
 weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const resultsData = [
 {
  id: 1,
  percentage: "23",
  detail:
   "Decrease in Cost Per Acquisition (CPA) by 23%. Proper tracking allows for more efficient ad targeting and budget allocation, leading to a significant reduction in the cost to acquire a new customer.",
 },
 {
  id: 2,
  percentage: "37",
  detail:
   "Increase in Return on Ad Spend (ROAS) by 37%. With accurate conversion tracking, businesses can optimize their ad campaigns for better performance, resulting in a higher return on their advertising investments.",
 },
 {
  id: 3,
  percentage: "19",
  detail:
   "Improvement in conversion attribution accuracy by 19%. Enhanced tracking provides clearer insights into the customer journey, allowing businesses to attribute conversions more accurately to the correct marketing channels.",
 },
 {
  id: 4,
  percentage: "27",
  detail:
   "Increase in Customer Lifetime Value (LTV) by 27%. By understanding customer behavior through detailed analytics, businesses can tailor their marketing strategies to increase the overall value generated by each customer over time.",
 },
];

function page() {
 return (
  <div className={`${poppins.className}`}>
   <header className=' bg-dark-primary w-full'>
    <div className='container-primary'>
     <div className='hidden lg:block'>
      <DesktopNav />
     </div>
     <MobileNav />
    </div>
   </header>

   <main className=''>
    <section className='gap-4 py-10 flex items-center flex-col text-center container-primary'>
     <Hero />
    </section>

    <section>
     <ImageSlider />
    </section>

    <section className='py-20 gap-5 flex items-center flex-col container-primary'>
     <WorkHistory />
    </section>

    <section
     id='why-us'
     className='pt-3 flex items-center flex-col container-primary'>
     <ReasonsData />
    </section>

    <section className='flex flex-col items-center container-primary md:py-10'>
     <ReasonsData02 />
    </section>

    <section className='px-3'>
     <CallToAction />
    </section>

    <section
     id='about'
     className='grid md:grid-cols-2 pt-20 items-end justify-center container-primary'>
     <div className='pr-10 pl-3'>
      <p className='text-primary text-center md:text-left'>
       Here's why you should trust Tracking Academy
      </p>
      <h2 className='title-secondary text-light-primary text-center md:text-left'>
       We are the experts in Analytics Integration that's Accurate.
      </h2>
      <p className='py-6 paragraph-primary text-center md:text-left'>
       Our founder, Ali Hassan, has configured and audited more than 1,000
       websites for eCommerce brands and lead generation websites with Google
       Analytics 4, Google Tag Manager, Facebook Pixel and more.
      </p>
      <p className='md:py-6 paragraph-primary text-center md:text-left'>
       After making hundreds of tracking integration and system for clients and
       agencies, Hassan put together a world-class team of strategists,
       Analysts, marketers, developers, and a conversion tracking experts that
       led to launch Tracking Academy — the most effective web analytics
       integration agency used by category-defining brands and agencies.
      </p>
     </div>

     <div className='relative w-full pt-4'>
      <Image
       className='w-full grayscale'
       width={1185}
       height={1080}
       src='/images/hero/about-image.png'
       alt='Imtiaz Ahmed'
      />
     </div>
    </section>
    <section className='bg-light-primary '>
     <div className='flex items-center flex-col container-primary px-4 py-20'>
      <p className='text-secondary font-semibold'>It works, too</p>
      <h2 className='title-secondary text-center text-dark-primary container-secondary'>
       As you can see for yourself, we get results
      </h2>
      <div className='grid md:grid-cols-4 gap-2 pt-16 w-full'>
       {resultsData.map((result, index) => (
        <div key={index} className='bg-dark-primary border rounded-lg p-8'>
         <p className='title-primary pb-5'> {result.percentage}% </p>
         <p className='paragraph-secondary'>{result.detail} </p>
        </div>
       ))}
      </div>
      <p className='pt-16 paragraph-tertiary text-dark-primary text-center'>
       Results may vary*
      </p>
     </div>
    </section>

    <section className='py-20 container-primary flex flex-col items-center'>
     <h2 className='title-secondary text-center py-10 container-secondary'>
      What happens when you purchase a Tracking Package
     </h2>
     <Timeline />
    </section>

    <section id='case-studies' className='bg-light-primary'>
     <CaseStudies />
    </section>
    <section
     id='call-to-action'
     className='grid md:grid-cols-2 gap-4 py-10 items-center justify-center container-primary'>
     <div className='space-y-4 '>
      <p className='text-primary'>Let's Enhance Your Digital Presence</p>
      <h2 className='title-primary'>Analytics & Tracking Solutions</h2>
      <p className='paragraph-primary'>
       We specialize in configuring advanced tracking and analytics for your
       website, ensuring you capture every interaction and gain insights that
       drive growth.
      </p>
      <p className='paragraph-primary'>
       Our solutions empower you to understand your audience, optimize your
       marketing strategies, and achieve higher conversion rates with
       data-driven decisions.
      </p>
     </div>

     <div className='bg-primary rounded-lg py-10 px-6 text-dark-primary divide-y divide-dark-secondary'>
      <div className='pb-3'>
       <h3 className='title-tertiary font-bold'>Analytics Setup Package</h3>
       <div className='py-4 flex items-center gap-4'>
        <p className='paragraph-secondary font-bold'>$3,000</p>
        <p className='paragraph-tertiary'>
         Comprehensive analytics and tracking setup
        </p>
       </div>
      </div>
      <div className='py-4 paragraph-secondary'>
       <p className='font-bold pt-3 pb-4'>What's Included</p>
       <ul className='list-inside grid gap-4 sm:grid-cols-2 md:grid-cols-1 lg:grid-cols-2'>
        <li className='flex items-center'>✔ Google Analytics Setup</li>
        <li className='flex items-center'>
         ✔ Google Tag Manager Configuration
        </li>
        <li className='flex items-center'>✔ Conversion Tracking</li>
        <li className='flex items-center'>✔ Custom Event Tracking</li>
        <li className='flex items-center'>✔ E-commerce Tracking</li>
        <li className='flex items-center'>✔ Data Layer Implementation</li>
        <li className='flex items-center'>✔ Dashboard & Report Setup</li>
        <li className='flex items-center'>✔ Ongoing Support & Optimization</li>
       </ul>
      </div>
      <button className='link-secondary w-full mt-6 p-4 !text-light-primary'>
       Get Started with Analytics
      </button>
     </div>
    </section>

    <section className='pb-20 bg-light-primary'>
     <div className='container-primary py-20 text-dark-primary text-center '>
      <h2 className='title-secondary py-8'>We plug into your tech stack</h2>
      <Technologies />
     </div>
     <div className='text-dark-primary'>
      <h2 className='title-secondary text-center'>How we compare</h2>
      <div className=' flex items-center justify-center py-6'>
       <p className='paragraph-primary container-secondary text-center'>
        At Tracking Academy, we understand the importance of seamless
        integration with your existing tech stack. Our analytics and tracking
        solutions are designed to work effortlessly with your marketing tools,
        providing you with a unified view of your digital performance and
        enabling more effective decision-making.
       </p>
      </div>
      <ComparisonTable />
     </div>
    </section>
    <section className='py-20'>
     <h2 className='title-primary container-primary py-12 text-center'>
      What others have to say about working with Tracking Academy
     </h2>
     <div>
      <ImageSlider />
     </div>
     <div className='flex gap-x-2 md:gap-x-4 py-20 container-primary items-center justify-center'>
      <Link href='/contact' className='link-primary  px-4 md:px-16 py-3'>
       Book a Call
      </Link>
      <Link href='/#why-us' className='link-secondary px-4 md:px-16 py-3'>
       Get Started
      </Link>
     </div>
    </section>

    <section className='bg-light-primary text-dark-primary py-20'>
     <h2 className='title-primary container-primary text-center py-12'>
      Frequently Asked Questions
     </h2>
     <div className='container-secondary'>
      <FAQ />
     </div>
    </section>
    <section className='bg-light-primary pb-20'>
     <div className='grid md:grid-cols-2 gap-4 md:gap-8 container-primary'>
      <div className='bg-primary rounded-lg flex flex-col justify-between text-dark-primary'>
       <div className='pb-3 pt-10 pr-10 pl-10 md:pr-16 md:pl-16 md:pt-16'>
        <h3 className='title-tertiary font-bold'>
         Ready to Enhance Your Analytics & Tracking?
        </h3>
        <div className='py-4 flex items-center gap-4 pb-8'>
         <p className='paragraph-tertiary'>
          Discover why brands like Bookonline, TicketOnline, and Comrade trust
          us for their analytics and tracking needs.
         </p>
        </div>
        <Link
         href='/services/web-analytics-and-tracking'
         className='link-secondary w-full flex items-center justify-center text-light-primary py-3'>
         Get Started
        </Link>
       </div>

       <div className='relative w-full pt-4'>
        <Image
         className='w-full grayscale'
         width={1185}
         height={1080}
         src='/images/hero/about-image.png'
         alt='Imtiaz Ahmed'
        />
       </div>
      </div>
      <div className='bg-dark-primary rounded-lg text-light-primary flex flex-col justify-between '>
       <div className='pb-3  pt-10 pr-10 pl-10 md:pr-16 md:pl-16 md:pt-16'>
        <h3 className='title-tertiary font-bold'>
         Not ready to start yet? Book a consultation 🤙
        </h3>
        <div className='py-4 flex items-center gap-4  pb-8'>
         <p className='paragraph-tertiary'>
          Schedule a call to discuss how our expertise in analytics and tracking
          can boost your marketing efforts.
         </p>
        </div>
        <Link
         href='/contact'
         className='link-primary w-full flex items-center justify-center py-3'>
         Book a Call
        </Link>
       </div>
       <div className='relative w-full pt-4'>
        <Image
         className='w-full grayscale'
         width={1185}
         height={1080}
         src='/images/hero/about-image.png'
         alt='Imtiaz Ahmed'
        />
       </div>
      </div>
     </div>
    </section>
   </main>

   <Footer />
  </div>
 );
}

export default page;
